name: Build docs

on:
  workflow_dispatch:
  push:
      branches:
        - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # HOTFIX for https://github.com/actions/runner/issues/2033
      - name: Fix git safe.directory in container
        run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\n\tdirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig

      - name: Build and deploy docs with mike
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IsRevisionDatePluginEnabled: "true"
          IsAuthorsPluginEnabled: "true"
        with:
          args: sh -c "git config --global  user.name github-actions[bot];git config --global user.email "github-actions[bot]@users.noreply.github.com";mike deploy --push 2024" # the git config is still not available for mike
          
